name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Set up CML
      uses: iterative/setup-cml@v2

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main file
      run: |
        python main.py || exit 1  # Exit with an error code if the script fails

    - name: Run Tests
      run: |
        python -m unittest discover || exit 1  # Exit with an error code if tests fail

    - name: Debug
      run: |
        ls -R

    - name: Create CML report
      env:
        REPO_TOKEN: ${{ secrets.HffdjjfsgnGhjan }}
      run: |
        echo "# First Line of our report" >> report.md
        echo "## Plots" >> report.md
        echo "![Bar plot](${GITHUB_WORKSPACE}/confusion_matrix_plot.png 'Bar plot')" >> report.md

        # Publish the CML report
        cml publish report.md || exit 1  # Exit with an error code if report publishing fails
